package de.htwberlin.learningcompanion.util

val LIGHT_LOW_THRESHOLD = 30.0
val LIGHT_MEDIUM_THRESHOLD = 50.0
val LIGHT_HIGH_THRESHOLD = 100.0
val LIGHT_HIGHEST_THRESHOLD = 150.0

val NOISE_LOW_THRESHOLD = 2000.0
val NOISE_MEDIUM_THRESHOLD = 5000.0
val NOISE_HIGH_THRESHOLD = 8000.0
val NOISE_HIGHEST_THRESHOLD = 1000.0

/*
val LIGHT_LOW_THRESHOLD = 30.0
val LIGHT_MEDIUM_THRESHOLD = 400.0 // average ambient light in room at noon
val LIGHT_HIGH_THRESHOLD = 100.0
val LIGHT_HIGHEST_THRESHOLD = 150.0
*/